package id.psw.qsbadapple

class DisplayTile00 : DisplayTileService(0,0)
class DisplayTile10 : DisplayTileService(1,0)
class DisplayTile20 : DisplayTileService(2,0)
class DisplayTile30 : DisplayTileService(3,0)
class DisplayTile01 : DisplayTileService(0,1)
class DisplayTile11 : DisplayTileService(1,1)
class DisplayTile21 : DisplayTileService(2,1)
class DisplayTile31 : DisplayTileService(3,1)
class DisplayTile02 : DisplayTileService(0,2)
class DisplayTile12 : DisplayTileService(1,2)
class DisplayTile22 : DisplayTileService(2,2)
class DisplayTile32 : DisplayTileService(3,2)
class DisplayTile03 : DisplayTileService(0,3)
class DisplayTile13 : DisplayTileService(1,3)
class DisplayTile23 : DisplayTileService(2,3)
class DisplayTile33 : DisplayTileService(3,3)